/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2010-2012 Oracle and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * http://glassfish.java.net/public/CDDL+GPL_1_1.html
 * or packager/legal/LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at packager/legal/LICENSE.txt.
 *
 * GPL Classpath Exception:
 * Oracle designates this particular file as subject to the "Classpath"
 * exception as provided by Oracle in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.07.03 at 05:59:50 PM CEST
//


package org.glassfish.jersey.media.json.internal.rim;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.sun.jersey.json.impl.rim package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Metadata_QNAME = new QName("http://www.w3.org/2005/08/addressing", "Metadata");
    private final static QName _ProblemIRI_QNAME = new QName("http://www.w3.org/2005/08/addressing", "ProblemIRI");
    private final static QName _ParameterValue_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ParameterValue");
    private final static QName _ReplyTo_QNAME = new QName("http://www.w3.org/2005/08/addressing", "ReplyTo");
    private final static QName _RelatesTo_QNAME = new QName("http://www.w3.org/2005/08/addressing", "RelatesTo");
    private final static QName _RetryAfter_QNAME = new QName("http://www.w3.org/2005/08/addressing", "RetryAfter");
    private final static QName _Register_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Register");
    private final static QName _Service_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Service");
    private final static QName _ExternalIdentifier_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ExternalIdentifier");
    private final static QName _AuditableEvent_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "AuditableEvent");
    private final static QName _Classification_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Classification");
    private final static QName _ProblemHeaderQName_QNAME = new QName("http://www.w3.org/2005/08/addressing", "ProblemHeaderQName");
    private final static QName _AnyValue_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "AnyValue");
    private final static QName _ClassificationNode_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ClassificationNode");
    private final static QName _ServiceInterface_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ServiceInterface");
    private final static QName _ServiceBinding_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ServiceBinding");
    private final static QName _Subscription_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Subscription");
    private final static QName _ReferenceParameters_QNAME = new QName("http://www.w3.org/2005/08/addressing", "ReferenceParameters");
    private final static QName _ProblemAction_QNAME = new QName("http://www.w3.org/2005/08/addressing", "ProblemAction");
    private final static QName _Notification_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Notification");
    private final static QName _From_QNAME = new QName("http://www.w3.org/2005/08/addressing", "From");
    private final static QName _ExtrinsicObject_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ExtrinsicObject");
    private final static QName _EndpointReference_QNAME = new QName("http://www.w3.org/2005/08/addressing", "EndpointReference");
    private final static QName _ExternalLink_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ExternalLink");
    private final static QName _FaultTo_QNAME = new QName("http://www.w3.org/2005/08/addressing", "FaultTo");
    private final static QName _MessageID_QNAME = new QName("http://www.w3.org/2005/08/addressing", "MessageID");
    private final static QName _ServiceEndpoint_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ServiceEndpoint");
    private final static QName _Association_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Association");
    private final static QName _Registry_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Registry");
    private final static QName _RegistryPackage_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "RegistryPackage");
    private final static QName _StringValue_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "StringValue");
    private final static QName _Action_QNAME = new QName("http://www.w3.org/2005/08/addressing", "Action");
    private final static QName _QueryDefinition_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "QueryDefinition");
    private final static QName _Slot_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Slot");
    private final static QName _Federation_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Federation");
    private final static QName _Person_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Person");
    private final static QName _To_QNAME = new QName("http://www.w3.org/2005/08/addressing", "To");
    private final static QName _ObjectRefList_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ObjectRefList");
    private final static QName _IdentifiableList_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "IdentifiableList");
    private final static QName _Organization_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Organization");
    private final static QName _Comment_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "Comment");
    private final static QName _RegistryObjectList_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "RegistryObjectList");
    private final static QName _ClassificationScheme_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", "ClassificationScheme");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.jersey.json.impl.rim
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObjectRefType }
     *
     */
    public ObjectRefType createObjectRefType() {
        return new ObjectRefType();
    }

    /**
     * Create an instance of {@link NotificationType }
     *
     */
    public NotificationType createNotificationType() {
        return new NotificationType();
    }

    /**
     * Create an instance of {@link LocalizedStringType }
     *
     */
    public LocalizedStringType createLocalizedStringType() {
        return new LocalizedStringType();
    }

    /**
     * Create an instance of {@link AttributedQNameType }
     *
     */
    public AttributedQNameType createAttributedQNameType() {
        return new AttributedQNameType();
    }

    /**
     * Create an instance of {@link AnyValueType }
     *
     */
    public AnyValueType createAnyValueType() {
        return new AnyValueType();
    }

    /**
     * Create an instance of {@link SimpleLinkType }
     *
     */
    public SimpleLinkType createSimpleLinkType() {
        return new SimpleLinkType();
    }

    /**
     * Create an instance of {@link SubscriptionType }
     *
     */
    public SubscriptionType createSubscriptionType() {
        return new SubscriptionType();
    }

    /**
     * Create an instance of {@link AttributedURIType }
     *
     */
    public AttributedURIType createAttributedURIType() {
        return new AttributedURIType();
    }

    /**
     * Create an instance of {@link ExtrinsicObjectType }
     *
     */
    public ExtrinsicObjectType createExtrinsicObjectType() {
        return new ExtrinsicObjectType();
    }

    /**
     * Create an instance of {@link FederationType }
     *
     */
    public FederationType createFederationType() {
        return new FederationType();
    }

    /**
     * Create an instance of {@link SlotType }
     *
     */
    public SlotType createSlotType() {
        return new SlotType();
    }

    /**
     * Create an instance of {@link ObjectRefListType }
     *
     */
    public ObjectRefListType createObjectRefListType() {
        return new ObjectRefListType();
    }

    /**
     * Create an instance of {@link PersonType }
     *
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link DeliveryInfoType }
     *
     */
    public DeliveryInfoType createDeliveryInfoType() {
        return new DeliveryInfoType();
    }

    /**
     * Create an instance of {@link RegistryObjectType }
     *
     */
    public RegistryObjectType createRegistryObjectType() {
        return new RegistryObjectType();
    }

    /**
     * Create an instance of {@link EndpointReferenceType }
     *
     */
    public EndpointReferenceType createEndpointReferenceType() {
        return new EndpointReferenceType();
    }

    /**
     * Create an instance of {@link AuditableEventType }
     *
     */
    public AuditableEventType createAuditableEventType() {
        return new AuditableEventType();
    }

    /**
     * Create an instance of {@link ActionType }
     *
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link MetadataType }
     *
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     *
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

    /**
     * Create an instance of {@link ServiceEndpointType }
     *
     */
    public ServiceEndpointType createServiceEndpointType() {
        return new ServiceEndpointType();
    }

    /**
     * Create an instance of {@link ClassificationSchemeType }
     *
     */
    public ClassificationSchemeType createClassificationSchemeType() {
        return new ClassificationSchemeType();
    }

    /**
     * Create an instance of {@link TelephoneNumberType }
     *
     */
    public TelephoneNumberType createTelephoneNumberType() {
        return new TelephoneNumberType();
    }

    /**
     * Create an instance of {@link ServiceType }
     *
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link InternationalStringType }
     *
     */
    public InternationalStringType createInternationalStringType() {
        return new InternationalStringType();
    }

    /**
     * Create an instance of {@link RegistryType }
     *
     */
    public RegistryType createRegistryType() {
        return new RegistryType();
    }

    /**
     * Create an instance of {@link AttributedUnsignedLongType }
     *
     */
    public AttributedUnsignedLongType createAttributedUnsignedLongType() {
        return new AttributedUnsignedLongType();
    }

    /**
     * Create an instance of {@link ExternalIdentifierType }
     *
     */
    public ExternalIdentifierType createExternalIdentifierType() {
        return new ExternalIdentifierType();
    }

    /**
     * Create an instance of {@link AssociationType }
     *
     */
    public AssociationType createAssociationType() {
        return new AssociationType();
    }

    /**
     * Create an instance of {@link ProblemActionType }
     *
     */
    public ProblemActionType createProblemActionType() {
        return new ProblemActionType();
    }

    /**
     * Create an instance of {@link RelatesToType }
     *
     */
    public RelatesToType createRelatesToType() {
        return new RelatesToType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     *
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link QueryDefinitionType }
     *
     */
    public QueryDefinitionType createQueryDefinitionType() {
        return new QueryDefinitionType();
    }

    /**
     * Create an instance of {@link RegistryObjectListType }
     *
     */
    public RegistryObjectListType createRegistryObjectListType() {
        return new RegistryObjectListType();
    }

    /**
     * Create an instance of {@link EmailAddressType }
     *
     */
    public EmailAddressType createEmailAddressType() {
        return new EmailAddressType();
    }

    /**
     * Create an instance of {@link CommentType }
     *
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     *
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link RegistryPackageType }
     *
     */
    public RegistryPackageType createRegistryPackageType() {
        return new RegistryPackageType();
    }

    /**
     * Create an instance of {@link ExternalLinkType }
     *
     */
    public ExternalLinkType createExternalLinkType() {
        return new ExternalLinkType();
    }

    /**
     * Create an instance of {@link VersionInfoType }
     *
     */
    public VersionInfoType createVersionInfoType() {
        return new VersionInfoType();
    }

    /**
     * Create an instance of {@link ClassificationNodeType }
     *
     */
    public ClassificationNodeType createClassificationNodeType() {
        return new ClassificationNodeType();
    }

    /**
     * Create an instance of {@link RegisterType }
     *
     */
    public RegisterType createRegisterType() {
        return new RegisterType();
    }

    /**
     * Create an instance of {@link ServiceBindingType }
     *
     */
    public ServiceBindingType createServiceBindingType() {
        return new ServiceBindingType();
    }

    /**
     * Create an instance of {@link DynamicObjectRefType }
     *
     */
    public DynamicObjectRefType createDynamicObjectRefType() {
        return new DynamicObjectRefType();
    }

    /**
     * Create an instance of {@link ParameterType }
     *
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link StringQueryExpressionType }
     *
     */
    public StringQueryExpressionType createStringQueryExpressionType() {
        return new StringQueryExpressionType();
    }

    /**
     * Create an instance of {@link StringValueType }
     *
     */
    public StringValueType createStringValueType() {
        return new StringValueType();
    }

    /**
     * Create an instance of {@link ReferenceParametersType }
     *
     */
    public ReferenceParametersType createReferenceParametersType() {
        return new ReferenceParametersType();
    }

    /**
     * Create an instance of {@link ValueListType }
     *
     */
    public ValueListType createValueListType() {
        return new ValueListType();
    }

    /**
     * Create an instance of {@link IdentifiableListType }
     *
     */
    public IdentifiableListType createIdentifiableListType() {
        return new IdentifiableListType();
    }

    /**
     * Create an instance of {@link ServiceInterfaceType }
     *
     */
    public ServiceInterfaceType createServiceInterfaceType() {
        return new ServiceInterfaceType();
    }

    /**
     * Create an instance of {@link QueryType }
     *
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link XMLQueryExpressionType }
     *
     */
    public XMLQueryExpressionType createXMLQueryExpressionType() {
        return new XMLQueryExpressionType();
    }

    /**
     * Create an instance of {@link ParameterValueType }
     *
     */
    public ParameterValueType createParameterValueType() {
        return new ParameterValueType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     *
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "Metadata")
    public JAXBElement<MetadataType> createMetadata(MetadataType value) {
        return new JAXBElement<MetadataType>(_Metadata_QNAME, MetadataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedURIType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "ProblemIRI")
    public JAXBElement<AttributedURIType> createProblemIRI(AttributedURIType value) {
        return new JAXBElement<AttributedURIType>(_ProblemIRI_QNAME, AttributedURIType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterValueType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ParameterValue")
    public JAXBElement<ParameterValueType> createParameterValue(ParameterValueType value) {
        return new JAXBElement<ParameterValueType>(_ParameterValue_QNAME, ParameterValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointReferenceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "ReplyTo")
    public JAXBElement<EndpointReferenceType> createReplyTo(EndpointReferenceType value) {
        return new JAXBElement<EndpointReferenceType>(_ReplyTo_QNAME, EndpointReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatesToType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "RelatesTo")
    public JAXBElement<RelatesToType> createRelatesTo(RelatesToType value) {
        return new JAXBElement<RelatesToType>(_RelatesTo_QNAME, RelatesToType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedUnsignedLongType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "RetryAfter")
    public JAXBElement<AttributedUnsignedLongType> createRetryAfter(AttributedUnsignedLongType value) {
        return new JAXBElement<AttributedUnsignedLongType>(_RetryAfter_QNAME, AttributedUnsignedLongType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Register")
    public JAXBElement<RegisterType> createRegister(RegisterType value) {
        return new JAXBElement<RegisterType>(_Register_QNAME, RegisterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Service")
    public JAXBElement<ServiceType> createService(ServiceType value) {
        return new JAXBElement<ServiceType>(_Service_QNAME, ServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalIdentifierType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ExternalIdentifier")
    public JAXBElement<ExternalIdentifierType> createExternalIdentifier(ExternalIdentifierType value) {
        return new JAXBElement<ExternalIdentifierType>(_ExternalIdentifier_QNAME, ExternalIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuditableEventType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "AuditableEvent")
    public JAXBElement<AuditableEventType> createAuditableEvent(AuditableEventType value) {
        return new JAXBElement<AuditableEventType>(_AuditableEvent_QNAME, AuditableEventType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassificationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Classification")
    public JAXBElement<ClassificationType> createClassification(ClassificationType value) {
        return new JAXBElement<ClassificationType>(_Classification_QNAME, ClassificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedQNameType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "ProblemHeaderQName")
    public JAXBElement<AttributedQNameType> createProblemHeaderQName(AttributedQNameType value) {
        return new JAXBElement<AttributedQNameType>(_ProblemHeaderQName_QNAME, AttributedQNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyValueType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "AnyValue")
    public JAXBElement<AnyValueType> createAnyValue(AnyValueType value) {
        return new JAXBElement<AnyValueType>(_AnyValue_QNAME, AnyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassificationNodeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ClassificationNode")
    public JAXBElement<ClassificationNodeType> createClassificationNode(ClassificationNodeType value) {
        return new JAXBElement<ClassificationNodeType>(_ClassificationNode_QNAME, ClassificationNodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceInterfaceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ServiceInterface")
    public JAXBElement<ServiceInterfaceType> createServiceInterface(ServiceInterfaceType value) {
        return new JAXBElement<ServiceInterfaceType>(_ServiceInterface_QNAME, ServiceInterfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceBindingType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ServiceBinding")
    public JAXBElement<ServiceBindingType> createServiceBinding(ServiceBindingType value) {
        return new JAXBElement<ServiceBindingType>(_ServiceBinding_QNAME, ServiceBindingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscriptionType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Subscription")
    public JAXBElement<SubscriptionType> createSubscription(SubscriptionType value) {
        return new JAXBElement<SubscriptionType>(_Subscription_QNAME, SubscriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceParametersType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "ReferenceParameters")
    public JAXBElement<ReferenceParametersType> createReferenceParameters(ReferenceParametersType value) {
        return new JAXBElement<ReferenceParametersType>(_ReferenceParameters_QNAME, ReferenceParametersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProblemActionType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "ProblemAction")
    public JAXBElement<ProblemActionType> createProblemAction(ProblemActionType value) {
        return new JAXBElement<ProblemActionType>(_ProblemAction_QNAME, ProblemActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Notification")
    public JAXBElement<NotificationType> createNotification(NotificationType value) {
        return new JAXBElement<NotificationType>(_Notification_QNAME, NotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointReferenceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "From")
    public JAXBElement<EndpointReferenceType> createFrom(EndpointReferenceType value) {
        return new JAXBElement<EndpointReferenceType>(_From_QNAME, EndpointReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtrinsicObjectType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ExtrinsicObject")
    public JAXBElement<ExtrinsicObjectType> createExtrinsicObject(ExtrinsicObjectType value) {
        return new JAXBElement<ExtrinsicObjectType>(_ExtrinsicObject_QNAME, ExtrinsicObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointReferenceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "EndpointReference")
    public JAXBElement<EndpointReferenceType> createEndpointReference(EndpointReferenceType value) {
        return new JAXBElement<EndpointReferenceType>(_EndpointReference_QNAME, EndpointReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalLinkType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ExternalLink")
    public JAXBElement<ExternalLinkType> createExternalLink(ExternalLinkType value) {
        return new JAXBElement<ExternalLinkType>(_ExternalLink_QNAME, ExternalLinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointReferenceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "FaultTo")
    public JAXBElement<EndpointReferenceType> createFaultTo(EndpointReferenceType value) {
        return new JAXBElement<EndpointReferenceType>(_FaultTo_QNAME, EndpointReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedURIType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "MessageID")
    public JAXBElement<AttributedURIType> createMessageID(AttributedURIType value) {
        return new JAXBElement<AttributedURIType>(_MessageID_QNAME, AttributedURIType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceEndpointType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ServiceEndpoint")
    public JAXBElement<ServiceEndpointType> createServiceEndpoint(ServiceEndpointType value) {
        return new JAXBElement<ServiceEndpointType>(_ServiceEndpoint_QNAME, ServiceEndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssociationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Association")
    public JAXBElement<AssociationType> createAssociation(AssociationType value) {
        return new JAXBElement<AssociationType>(_Association_QNAME, AssociationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Registry")
    public JAXBElement<RegistryType> createRegistry(RegistryType value) {
        return new JAXBElement<RegistryType>(_Registry_QNAME, RegistryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryPackageType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "RegistryPackage")
    public JAXBElement<RegistryPackageType> createRegistryPackage(RegistryPackageType value) {
        return new JAXBElement<RegistryPackageType>(_RegistryPackage_QNAME, RegistryPackageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringValueType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "StringValue")
    public JAXBElement<StringValueType> createStringValue(StringValueType value) {
        return new JAXBElement<StringValueType>(_StringValue_QNAME, StringValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedURIType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "Action")
    public JAXBElement<AttributedURIType> createAction(AttributedURIType value) {
        return new JAXBElement<AttributedURIType>(_Action_QNAME, AttributedURIType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDefinitionType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "QueryDefinition")
    public JAXBElement<QueryDefinitionType> createQueryDefinition(QueryDefinitionType value) {
        return new JAXBElement<QueryDefinitionType>(_QueryDefinition_QNAME, QueryDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlotType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Slot")
    public JAXBElement<SlotType> createSlot(SlotType value) {
        return new JAXBElement<SlotType>(_Slot_QNAME, SlotType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FederationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Federation")
    public JAXBElement<FederationType> createFederation(FederationType value) {
        return new JAXBElement<FederationType>(_Federation_QNAME, FederationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedURIType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/08/addressing", name = "To")
    public JAXBElement<AttributedURIType> createTo(AttributedURIType value) {
        return new JAXBElement<AttributedURIType>(_To_QNAME, AttributedURIType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectRefListType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ObjectRefList")
    public JAXBElement<ObjectRefListType> createObjectRefList(ObjectRefListType value) {
        return new JAXBElement<ObjectRefListType>(_ObjectRefList_QNAME, ObjectRefListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifiableListType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "IdentifiableList")
    public JAXBElement<IdentifiableListType> createIdentifiableList(IdentifiableListType value) {
        return new JAXBElement<IdentifiableListType>(_IdentifiableList_QNAME, IdentifiableListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Organization")
    public JAXBElement<OrganizationType> createOrganization(OrganizationType value) {
        return new JAXBElement<OrganizationType>(_Organization_QNAME, OrganizationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "Comment")
    public JAXBElement<CommentType> createComment(CommentType value) {
        return new JAXBElement<CommentType>(_Comment_QNAME, CommentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryObjectListType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "RegistryObjectList")
    public JAXBElement<RegistryObjectListType> createRegistryObjectList(RegistryObjectListType value) {
        return new JAXBElement<RegistryObjectListType>(_RegistryObjectList_QNAME, RegistryObjectListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassificationSchemeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0", name = "ClassificationScheme")
    public JAXBElement<ClassificationSchemeType> createClassificationScheme(ClassificationSchemeType value) {
        return new JAXBElement<ClassificationSchemeType>(_ClassificationScheme_QNAME, ClassificationSchemeType.class, null, value);
    }

}
